# Generated by Django 5.1.5 on 2025-01-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_institution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
    ]
